# The 'type' should be "label" for short meta tags and "text" for ones which
# could get longer, especially ones which use a textarea field instead of a
# textfield.
metatag.metatag_tag.schema_service_type:
  type: text
  label: '@type'
metatag.metatag_tag.schema_service_description:
  type: text
  label: 'asset'
metatag.metatag_tag.schema_service_name:
  type: text
  label: 'name'
metatag.metatag_tag.schema_service_description:
  type: text
  label: 'description'
