google_analytics_id: ''
google_adsense_id: ''
google_doubleclick_id: ''
amp_pixel: 0
amp_pixel_domain_name: ''
amp_pixel_query_string: ''
amp_pixel_random_number: 0
amp_library_process_full_html: 0
amp_library_process_full_html_warnings: 0
amp_library_process_statistics: 0
amp_library_warnings_display: 0
