module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  amp: 0
  audiofield: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_views_select: 0
  eva: 0
  feeds: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  focal_point: 0
  help: 0
  history: 0
  image: 0
  image_effects: 0
  kint: 0
  link: 0
  media: 0
  media_bulk_upload: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  schema_article: 0
  schema_metatag: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  amptheme: 0
  ampsubtheme_example: 0
  lenstheme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
